tube_storage_config = {
    # Zn(Gly)2
    1: {"smiles": "NCC(=O)O[Zn]OC(=O)CN", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    9: {"smiles": "NCC(=O)O[Zn]OC(=O)CN", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    17: {"smiles": "NCC(=O)O[Zn]OC(=O)CN", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # Zn(Pro)2
    2: {"smiles": "O=C(O[Zn]OC(=O)C1CCCN1)C1CCCN1", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    10: {"smiles": "O=C(O[Zn]OC(=O)C1CCCN1)C1CCCN1", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    18: {"smiles": "O=C(O[Zn]OC(=O)C1CCCN1)C1CCCN1", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # Zn(Glu)2
    3: {"smiles": "NC(CCC(=O)O[Zn]OC(=O)CCC(N)C(O)=O)C(O)=O", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    11: {"smiles": "NC(CCC(=O)O[Zn]OC(=O)CCC(N)C(O)=O)C(O)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    19: {"smiles": "NC(CCC(=O)O[Zn]OC(=O)CCC(N)C(O)=O)C(O)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # Zn(Asp)2
    4: {"smiles": "NC(CC(N)=O)C(=O)O[Zn]OC(=O)C(N)CC(N)=O", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    12: {"smiles": "NC(CC(N)=O)C(=O)O[Zn]OC(=O)C(N)CC(N)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    20: {"smiles": "NC(CC(N)=O)C(=O)O[Zn]OC(=O)C(N)CC(N)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # Zn(Gln)2
    5: {"smiles": "NC(CCC(N)=O)C(=O)O[Zn]OC(=O)C(N)CCC(N)=O", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    13: {"smiles": "NC(CCC(N)=O)C(=O)O[Zn]OC(=O)C(N)CCC(N)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    21: {"smiles": "NC(CCC(N)=O)C(=O)O[Zn]OC(=O)C(N)CCC(N)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # Zn(Ile)2
    6: {"smiles": "CCC(C)C(N)C(=O)O[Zn]OC(=O)C(N)C(C)CC", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    14: {"smiles": "CCC(C)C(N)C(=O)O[Zn]OC(=O)C(N)C(C)CC", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    22: {"smiles": "CCC(C)C(N)C(=O)O[Zn]OC(=O)C(N)C(C)CC", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # Zn(Arg)2
    7: {"smiles": "NC(CCCNC(N)=N)C(=O)O[Zn]OC(=O)C(N)CCCNC(N)=N", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    15: {"smiles": "NC(CCCNC(N)=N)C(=O)O[Zn]OC(=O)C(N)CCCNC(N)=N", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    23: {"smiles": "NC(CCCNC(N)=N)C(=O)O[Zn]OC(=O)C(N)CCCNC(N)=N", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    # Zn(His)2
    8: {"smiles": "NC(Cc1c[nH]cn1)C(=O)O[Zn]OC(=O)C(N)Cc1c[nH]cn1", "volume": 0.001, "mols": None, "state": "liquid",
        "density": 1.0,
        "concentration": 40e-6,
        "solvent": {"smiles": "O"}},
    16: {"smiles": "NC(Cc1c[nH]cn1)C(=O)O[Zn]OC(=O)C(N)Cc1c[nH]cn1", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},
    24: {"smiles": "NC(Cc1c[nH]cn1)C(=O)O[Zn]OC(=O)C(N)Cc1c[nH]cn1", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": 40e-6,
         "solvent": {"smiles": "O"}},

    # 2-nitrobenzaldehide in ACN
    49: {"smiles": "CC(=O)c1ccc(cc1)[N+]([O-])=O", "volume": 0.0015, "mols": None, "state": "liquid",
         "density": 1.02,
         "concentration": 300e-6,  # mM
         "solvent": {"smiles": "CC#N"}},
    50: {"smiles": "CC(=O)c1ccc(cc1)[N+]([O-])=O", "volume": 0.0015, "mols": None, "state": "liquid",
         "density": 1.02,
         "concentration": 300e-6,  # mM
         "solvent": {"smiles": "CC#N"}},
    51: {"smiles": "CC(=O)c1ccc(cc1)[N+]([O-])=O", "volume": 0.0015, "mols": None, "state": "liquid",
         "density": 1.02,
         "concentration": 300e-6,  # mM
         "solvent": {"smiles": "CC#N"}},
    52: {"smiles": "CC(=O)c1ccc(cc1)[N+]([O-])=O", "volume": 0.0015, "mols": None, "state": "liquid",
         "density": 1.02,
         "concentration": 300e-6,  # mM
         "solvent": {"smiles": "CC#N"}},

    # acetone
    65: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},
    66: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},
    67: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},
    68: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},
    69: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},
    70: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},
    71: {"smiles": "CC(C)=O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 0.784,
         "concentration": None,
         "solvent": {"smiles": None}},

    # water
    81: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    82: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    83: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    84: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    85: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    86: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    87: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    88: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    89: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    90: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    91: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    92: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    93: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    94: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    95: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}},
    96: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid",
         "density": 1.0,
         "concentration": None,
         "solvent": {"smiles": None}}

}

pipet_storage_config = {
    1: "blue_pipet",
    2: "blue_pipet",
    3: "blue_pipet",
    9: "blue_pipet",
    10: "blue_pipet",
    11: "blue_pipet",
    12: "blue_pipet",
    13: "blue_pipet",
    14: "blue_pipet",
}
reactor_config = {
    1: "available",
    2: "available",
    3: "available",
    4: "available",
}
big_storage_config = {
    1: {"smiles": "O", "volume": 0.001, "mols": None, "state": "liquid", "density": 1.0,
        "concentration": None,
        "solvent": {"smiles": None}},
}
